spring.application.name=Leave-Management
#Database connection URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=lms
#PostgreSQL username
spring.datasource.username=postgres
#PostgreSQL password
spring.datasource.password=3is
spring.datasource.driver-class-name=org.postgresql.Driver
#Automatically creates/updates tables
spring.jpa.hibernate.ddl-auto=update
#don't use space around = operateor
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true
#spring.jpa.hibernate.ddl-auto=update
#Prints SQL in the console
spring.jpa.show-sql=true
#Makes SQL easier to read
spring.jpa.properties.hibernate.format_sql=true
#Tells Hibernate to generate PostgreSQL-compatible SQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080


#crete log file in root directory of myu project
logging.file.name=/Users/Spring-ProjectWithPK/LeaveManagementSystem/logs/application.log

# Root log level
logging.level.root=INFO